### ISSUE TITLE
Close obj file after running project

### ISSUE THREAD

**Issue by gmuraru** [Eteru/ELF-Detective#4]
If you close an _object file_ after running the project (by mistake) you could not check the functions or the data from that _object file_ without closing the whole instance (in this case all the object files would be closed and you would have to reselect the _ELF_ and the _object files_).

**Comment by Eteru** [comment]
I can see why this feels like it can be improved, but "human error" is the reason I added a "Clear Project" button. It should feel better now that I've added support for multiple file selection for object files.

I will not allow the project to change after it ran because it will not scale well and this doesn't happen often enough to be a real issue.

Thanks for submitting this feedback.
